### PR TITLE
Issue 3: Add support for EMR Managed Scaling

### PR DESCRIPTION
**Pull request by mbadwalgithub**
*Issue:* https://github.com/awslabs/aws-emr-launch/issues/3

*Description of changes:* This change allows us to create EMR clusters with `ManagedScalingPolicy` applied to the cluster.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by chamcca** [comment]
at first glance this all looks good. we're still in the process of automating our regression tests, so in the meantime I'll need to manually run it through regression testing to ensure backwards compatibility before merging and publishing a release.

**Comment by mbadwalgithub** [comment]
Thanks @chamcca

**Comment by chamcca** [comment]
regression testing found a minor backwards incompatibility when a Launch Function attempts to use a previously stored Cluster Configuration that doesn't contain the `ManagedScalingPolicy` key. I have a fix for it, so merging here and will apply the fix. should be able to publish a release shortly thereafter.

**Comment by mbadwalgithub** [comment]
Thank you @chamcca

**Comment by pradeep5891** [comment]
Hi,
getting below error: any suggestions pls,
"Cluster: basic-cluster Terminated wuth errorsService-linked role 'AWSServiceRoleForEMRCleanup' for EM is required. Please create this role directly or add permission to create it in IAM entity"

But i can see this role roles list in AWS account while step function launch.

**Comment by chamcca** [comment]
is this the first time an EMR cluster has been created in the account? if so, you can either:

launch a cluster from the console using an IAM Role with permissions to create Roles. this will automatically create the Service Linked Role

or, use the AWS CLI and execute:
`aws iam create-service-linked-role --aws-service-name elasticmapreduce.amazonaws.com`
this will also need to be done using an IAM Role with permissions to create the Role

**Comment by pradeep5891** [comment]
Thank you @chamcca,

@chamcca,
If i want to edit or add below information, where i need to change , i mean the files and locations in those file, i am trying to use this as Iac.

1. Subnets (private and public)
2. security groups 
3. Autoscalling group
4. Nacl
5. Instance role for EMR
6. profiles to use KMS key

**Pull request merged**
